package com.truehr.app.domain.model

data class Profile(
  val employeeCode: String,
  val fullName: String,
  val isManager: Boolean,
  val designation: String,
  val department: String,
  val company: String,
  val dob: String?,
  val gender: String?,
  val phone: String?,
  val personalEmail: String?,
  val officialEmail: String?,
  val dateOfJoining: String?,
  val location: String?,
  val employmentType: String?,
  val reportingManager: String?,
  val functionalManager: String?,
  val address: String?,
  val permanentAddress: String?,
  val bankName: String?,
  val bankBranch: String?,
  val ifsc: String?,
  val accountNumber: String?,
  val pan: String?,
  val aadhaar: String?,
  val uan: String?,
  val pfNumber: String?,
  val esiNumber: String?,
)
