package com.truehr.app.presentation.navigation

object Routes {
  const val SPLASH = "splash"
  const val LOGIN = "login"
  const val CHANGE_PASSWORD = "change_password"
  const val DASHBOARD = "dashboard"
  const val PROFILE = "profile"
  const val PF = "pf"
  const val ATTENDANCE = "attendance"
  const val MARK_ATTENDANCE = "mark_attendance"
  const val DAILY_ATTENDANCE = "daily_attendance"
  const val MONTHLY_ATTENDANCE = "monthly_attendance"
  // per-member views (opened from Team Attendance)
  const val MEMBER_DAILY = "member_daily?eid={eid}&name={name}"
  fun memberDaily(eid: Long, name: String) =
    "member_daily?eid=$eid&name=${java.net.URLEncoder.encode(name, "UTF-8")}"
  const val MEMBER_MONTHLY = "member_monthly?eid={eid}&name={name}"
  fun memberMonthly(eid: Long, name: String) =
    "member_monthly?eid=$eid&name=${java.net.URLEncoder.encode(name, "UTF-8")}"
  const val TEAM_ATTENDANCE = "team_attendance"
  const val HOLD_TEAM_ATTENDANCE = "hold_team_attendance"
  const val APPLY_MISS_PUNCH = "apply_miss_punch"
  const val VIEW_MISS_PUNCH = "view_miss_punch"
  const val TEAM_MISS_PUNCH = "team_miss_punch"
  const val APPLY_OD = "apply_od"
  const val VIEW_OD = "view_od"
  const val TEAM_OD = "team_od"
  const val LEAVE = "leave"
  const val APPLY_LEAVE = "apply_leave"
  const val VIEW_LEAVE = "view_leave"
  const val TEAM_LEAVE = "team_leave"
  const val AVAIL_COMPOFF = "avail_compoff"
  const val TEAM_COMPOFF = "team_compoff"
  const val SALARY = "salary"
  const val SALARY_DETAIL = "salary_detail/{id}"
  fun salaryDetail(id: Long) = "salary_detail/$id"
  const val TEAM = "team"
  const val ADDRESS_BOOK = "address_book"
  const val POLICIES = "policies"
  const val SUPPORT = "support"
  const val SUPPORT_CREATE = "support_create/{cat}"
  fun supportCreate(cat: String) = "support_create/$cat"
  const val SUPPORT_VIEW = "support_view/{cat}"
  fun supportView(cat: String) = "support_view/$cat"
  const val RESIGNATION = "resignation"
  const val TEAM_RESIGNATION = "team_resignation"
  const val TOUR = "tour"
  const val TOUR_LIVE = "tour_live"
  const val TOUR_DETAILS = "tour_details"
  const val TOUR_ROUTE = "tour_route/{id}"
  fun tourRoute(id: Long) = "tour_route/$id"
  const val GEOTAG = "geotag"
  const val GEOTAG_LIST = "geotag_list"
  const val ESS = "ess"

  // generic feature route: feature/{title}
  const val FEATURE = "feature/{title}"
  fun feature(title: String) = "feature/$title"
}
